services:
  dappercrudplaygrounddb:
    container_name: dappercrudplaygrounddb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HardPassword12345678abc!
    restart: always
    ports:
      - "1488:1433"

  dappercrudplayground.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DbConnectionString=dappercrudplaygrounddb;Database=MoviesDb;User Id=sa;Password=HardPassword12345678abc!;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - dappercrudplaygrounddb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro