CREATE DATABASE MoviesDb;
GO

USE MoviesDb;
GO

CREATE TABLE movies (
    Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Director NVARCHAR(100) NOT NULL,
    ReleaseYear INT NOT NULL
);